routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', array('as'=>'index','uses'=>'ProgramController@index'));
Route::get('locale/{locale?}',array('as'=>'set-locale','uses'=>'AppController@setLocale'));
Route::get('/profile', array('as'=>'profile','uses'=>'UserController@getProfile'));
Route::resource('programs','ProgramController');

app/Models/Program.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
    protected $fillable = [

        'program_name',
        'program_price',
        'program_group'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AppController.php
<?php

namespace App\Http\Controllers;
use session;
use URL;

class AppController extends Controller
{
    public function setlocale($locale='tr'){
        if (!in_array($locale,['tr','en'])){
            $locale='tr';

        }
        Session::put('locale',$locale);
        return redirect(url(URL::previous()));

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
      // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProgramController.php
<?php

namespace App\Http\Controllers;

use phpDocumentor\Reflection\Types\Integer;
use Illuminate\Http\Request;
use App\Models\Program;
class ProgramController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $programs = Program::all();
        return view('programs.index',compact('programs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('programs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    $request->validate([
        'program_name'=>'required',
        'program_price'=>'required|integer',
        'program_group'=>'required|integer'
    ]);
    $program = new Program([

        'program_name'=>$request->get('program_name'),
        'program_price'=>$request->get('program_price'),
        'program_group'=>$request->get('program_group')
    ]);
    $program->save();
    return redirect('/programs')->with('success','Program Eklendi');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $program = Program::find($id);
        return view('programs.edit',compact('program'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'program_name'=>'required',
            'program_price'=>'required|integer',
            'program_group'=>'required|integer'
        ]);
        $program=Program::find($id);
        $program->program_name = $request->get('program_name');
        $program->program_price = $request->get('program_price');
        $program->program_group = $request->get('program_group');
        $program->save();
        return redirect('/programs')->with('success','Program Güncellendi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $program = Program::find($id);
        $program->delete();
        return redirect('/programs')->with('success','Program Silindi');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
         $this->middleware('auth');
    }
    public function getProfile()
    {
        return view('Layouts.profile');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                 {{Lang::get('lang.home')}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<head>
    <title>
        Program Projesi - ekle düzenle günelle sil </title>
        <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">

</head>
<body>
<div class="container">
    <a href="{{route('programs.create')}}">Yeni Program Ekle</a> -
    <a href="{{route('programs.index')}}">Program Listesi</a>-
    <a href="{{route('profile')}}">Profil Bilgileri</a>-
    <a href="{{route('login')}}">Üye Girişi</a>-

    @yield('content')

</div>
<script type="text/javascript" src="{{ asset('js/app.js')}}"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
       @include('layouts.header')

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
<div class="container">
<a class="navbar-brand" href="{{ url('/') }}">
{{ config('app.name', 'Laravel') }}
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<!-- Left Side Of Navbar -->
<ul class="navbar-nav mr-auto">

</ul>

<!-- Right Side Of Navbar -->
<ul class="navbar-nav ml-auto">
<!-- Authentication Links -->


@guest
<li class="nav-item">

    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
</li>
@if (Route::has('register'))

    <li class="nav-item">
        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
@endif
@else
<li class="nav-item dropdown">
    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="nav-link" href="{{ route('profile') }}">{{ __('kullanıcı bilgileri') }}</a>

        <a class="dropdown-item" href="{{ route('logout') }}"
           onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </div>
</li>
@endguest
</ul>
</div>
</div>
</nav>

resources/views/layouts/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Kullanıcı Bilgileri</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                            {{Auth::id()}} -

                        {{Auth::user()->email}}-
                        {{Auth::user()->name}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/programs/create.blade.php
@extends('layout')

@section('content')
    <div class="card uper">
        <div class="card-header">
            Program Ekle
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>

                </div>
            @endif
            <form method="post" action="{{route('programs.store')}}">
                <div class="form-group">
                    @csrf
                    <label for="program_name">Program Adı</label>
                    <input type="text" name="program_name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="program_price">Program Fiyatı</label>
                    <input type="text" name="program_price" class="form-control">
                </div>
                <div class="form-group">
                    <label for="program_group">Program Grubu</label>
                    <input type="text" name="program_group" class="form-control">
                </div>

                <button type="submit" class="btn btn-primary">kaydet</button>
            </form>
        </div>
    </div>
@endsection

resources/views/programs/edit.blade.php
@extends('layout')

@section('content')


    <div class="card uper">
    <div class="card-header">
        Program Düzenle
    </div>
        <div class="card-body">

            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>

                </div>
            @endif

                <form method="post" action="{{route('programs.update',$program->id)}}">
                @method('PATCH')
                    @csrf
                    <div class="form-group">
                        <label for="program_name">Program Adı</label>
                        <input type="text" name="program_name" class="form-control" value="{{$program->program_name}}">
                    </div>
                    <div class="form-group">
                        <label for="program_price">Program Fiyatı</label>
                        <input type="text" name="program_price" class="form-control" value="{{$program->program_price}}">
                    </div>
                    <div class="form-group">
                        <label for="program_group">Program Grubu</label>
                        <input type="text" name="program_group" class="form-control" value="{{$program->program_group}}">
                    </div>

                    <button type="submit" class="btn btn-primary">Güncelle</button>

                </form>
        </div>
    </div>
@endsection

resources/views/programs/index.blade.php
@extends('layout')

@section('content')

    <div class="uper">
        @if(session('success'))
            <div class="alert alert alert-success">
                {{session('success')}}
            </div>
            @endif
        <table class="table table-striped">
            <thead>
            <tr>
                <td>Program Adı</td>
                <td>Program Fiyatı</td>
                <td>Program Grubu</td>
                <td colspan="2"> İşlemler</td>

            </tr>

            </thead>
            <tbody>
            @foreach($programs as $program)
                <tr>
                    <td>{{ $program->program_name  }} </td>
                    <td>{{ $program->program_price  }}</td>
                    <td>{{ $program->program_group  }}</td>
                   <td>
                       <a class="btn btn-primary" href="{{ route('programs.edit',$program->id) }}">Düzenle</a>
                   </td>
                    <td>
<form action="{{route('programs.destroy',$program->id)}}" method="post">
    @csrf
    @method('DELETE')
    <button class="btn btn-danger" type="submit">Sil</button>
</form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endsection